config/routes.rb
Rails.application.routes.draw do
  get 'contato/index'
  get 'control_users/index'
  devise_for :users
  get 'welcome/index'
  root 'welcome#index'
  resources :roupas
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/roupa.rb
class Roupa < ApplicationRecord
	mount_uploader :picture, PictureUploader

end

app/models/user.rb
class User < ApplicationRecord
	enum role: [:normal_user, :admin]
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include Pundit
 
 	rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized


private
    

    def user_not_authorized
 	
 		flash[:notice] = "Você não tem permissão para fazer esta ação."
 		redirect_to(request.referrer || root_path)
 	
 	end


end

app/controllers/contato_controller.rb
class ContatoController < ApplicationController
  def index
  	
  end
end

app/controllers/control_users_controller.rb
class ControlUsersController < ApplicationController
  def index
  	@users = User.all
  	authorize @users
  end
end

app/controllers/roupas_controller.rb
class RoupasController < ApplicationController
  before_action :set_roupa, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /roupas
  # GET /roupas.json
  def index
    @roupas = Roupa.all
  end

  # GET /roupas/1
  # GET /roupas/1.json
  def show
  end

  # GET /roupas/new
  def new
    @roupa = Roupa.new
  end

  # GET /roupas/1/edit
  def edit
  end

  # POST /roupas
  # POST /roupas.json
  def create
    @roupa = Roupa.new(roupa_params)

    respond_to do |format|
      if @roupa.save
        format.html { redirect_to @roupa, notice: 'Roupa was successfully created.' }
        format.json { render :show, status: :created, location: @roupa }
      else
        format.html { render :new }
        format.json { render json: @roupa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roupas/1
  # PATCH/PUT /roupas/1.json
  def update
    respond_to do |format|
      if @roupa.update(roupa_params)
        format.html { redirect_to @roupa, notice: 'Roupa was successfully updated.' }
        format.json { render :show, status: :ok, location: @roupa }
      else
        format.html { render :edit }
        format.json { render json: @roupa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roupas/1
  # DELETE /roupas/1.json
  def destroy
    @roupa.destroy
    respond_to do |format|
      format.html { redirect_to roupas_url, notice: 'Roupa was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_roupa
      @roupa = Roupa.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def roupa_params
      params.require(:roupa).permit(:modelo, :preco, :picture)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@roupas = Roupa.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contato_helper.rb
module ContatoHelper
end

app/helpers/control_users_helper.rb
module ControlUsersHelper
end

app/helpers/roupas_helper.rb
module RoupasHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contato/index.html.erb
<h1>Contatos</h1>
<p>Email: emailteste.ep320191@gmail.com</p>
<p>Telefone: (61)0000-0000</p>

app/views/control_users/index.html.erb
<table>
  <thead>
    <tr>
      <th>email</th>
      <th>role</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.role %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ep3ThiagoKevin</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap-theme.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

<div class="container">
  <%= yield %>
</div>

<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Desde Pequena Tricô e Crochê</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "Entre em contato", contato_index_path %></li>
      </ul>
    </div>
  </div>
</nav>

  </body>
</html>

app/views/roupas/_form.html.erb
<%= form_with(model: roupa, local: true) do |form| %>
  <% if roupa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(roupa.errors.count, "error") %> prohibited this roupa from being saved:</h2>

      <ul>
      <% roupa.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :modelo %>
    <%= form.text_field :modelo %>
  </div>

  <div class="field">
    <%= form.label :preco %>
    <%= form.text_field :preco %>
  </div>

  <div class="field">
    <%= form.label :picture %>
    <%= form.file_field :picture %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/roupas/edit.html.erb
<h1>Editing Roupa</h1>

<%= render 'form', roupa: @roupa %>

<%= link_to 'Show', @roupa %> |
<%= link_to 'Back', roupas_path %>

app/views/roupas/index.html.erb
<p id="notice"><%= notice %></p>

<% if policy(@roupas).index? %>
<h1>Roupas</h1>

<table>
  <thead>
    <tr>
      <th>Modelo</th>
      <th>Preco</th>
      <th>Foto</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @roupas.each do |roupa| %>
      <tr>
        <td><%= roupa.modelo %></td>
        <td><%= roupa.preco %></td>
        <td><%= image_tag roupa.picture_url, width: '100%' if roupa.picture.present? %></td>
        <td><%= link_to 'Edit', edit_roupa_path(roupa) %></td>
        <td><%= link_to 'Destroy', roupa, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Nova Roupa', new_roupa_path %>

<% else %>

<h1>Roupas</h1>

<table>
  <thead>
    <tr>
      <th>Modelo</th>
      <th>Preco</th>
      <th>Foto</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @roupas.each do |roupa| %>
      <tr>
        <td><%= roupa.modelo %></td>
        <td><%= roupa.preco %></td>
        <td><%= image_tag roupa.picture_url, width: '100%' if roupa.picture.present? %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% end %>

app/views/roupas/new.html.erb
<h1>New Roupa</h1>

<%= render 'form', roupa: @roupa %>

<%= link_to 'Back', roupas_path %>

app/views/roupas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Modelo:</strong>
  <%= @roupa.modelo %>
</p>

<p>
  <strong>Preco:</strong>
  <%= @roupa.preco %>
</p>

<p>
  <strong>Picture:</strong>
  <%= image_tag(@roupa.picture_url, width: 600) if @roupa.picture.present? %>
</p>

<%= link_to 'Edit', edit_roupa_path(@roupa) %> |
<%= link_to 'Back', roupas_path %>

app/views/welcome/index.html.erb
<p id="notice"><%= notice %></p>
        <% if user_signed_in? %>
        <li><%= link_to "Sair", destroy_user_session_path, method: :delete %></li>
        <%else %>
        <li><%= link_to "Login", new_user_session_path %></li>
        <li><%= link_to "Cadastrar", new_user_registration_path %></li>
        <%end %>
        <li><%= link_to "Roupas", roupas_path %></li>

<table>
  <thead>
    <tr>
      <th>Modelo</th>
      <th>Preco</th>
      <th>Foto</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @roupas.each do |roupa| %>
      <tr>
        <td><%= roupa.modelo %></td>
        <td><%= roupa.preco %></td>
        <td><%= image_tag roupa.picture_url, width: '100%' if roupa.picture.present? %></td>
      </tr>
    <% end %>
  </tbody>
</table>